# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Copyright contributors to the vLLM project

TINY_SHENSI_KWARGS = {
    "vocab_size": 32,
    "hidden_size": 64,
    "moe_intermediate_size": 16,
    "routed_expert_hidden_size": 16,
    "num_hidden_layers": 4,
    "num_attention_heads": 4,
    "num_key_value_heads": 1,
    "head_dim": 64,
    "partial_rotary_factor": 0.25,
    "q_lora_rank": 16,
    "o_groups": 2,
    "o_lora_rank": 16,
    "index_head_dim": 16,
    "index_n_heads": 4,
    "index_topk": 8,
    "sliding_window": 8,
    "n_routed_experts": 4,
    "num_experts_per_tok": 2,
    "scoring_func": "sqrtsoftplus",
    "routed_scaling_factor": 1.5,
    "norm_topk_prob": True,
    "mlp_layer_types": ["hash_moe", "moe", "moe", "moe"],
    "layer_types": [
        "compressed_sparse_attention",
        "heavily_compressed_attention",
        "compressed_sparse_attention",
        "heavily_compressed_attention",
    ],
    "compress_rates": {
        "compressed_sparse_attention": 4,
        "heavily_compressed_attention": 128,
    },
    "compress_rope_theta": 160000.0,
    "hc_mult": 4,
    "hc_active_streams": 2,
    "hc_fixed_streams": 1,
    "hc_conv_kernels": (2, 3),
    "attn_res_block_size": 2,
    "swiglu_limit": 10.0,
    "rms_norm_eps": 1.0e-6,
    "rope_theta": 10000.0,
    "max_position_embeddings": 64,
    "num_nextn_predict_layers": 0,
}
